- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: latest

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install golang Dependencies
  ansible.builtin.shell: go mod init {{component}} ; go get ; go build
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
