- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: latest

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install golang Dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
